version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:8.9.2
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch
    networks:
      - elastic

  app: 
    build: ./app
    container_name: app
    depends_on:
      - elasticsearch
      - kibana
      - filebeat
    networks:
      - elastic 

networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local
