filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            equals:
              docker.container.name: "app"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "data"
      overwrite_keys: true
 
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

